name: Documentaci칩n autom치tica

on:
  push:
    branches: [ main, Principal, rama-colaborativa ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v3

      - name: Instalar MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Verificar archivos
        run: ls -R

      - name: Generar documentaci칩n
        run: mkdocs build
